In [1]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

import matplotlib.pyplot as plt

import torchvision
from torchvision import transforms,datasets

In [2]:
#creating the layers for FF neural network
class FFNeuralNet(nn.Module):                    #using nn.Module which is the base class for all neural networks
    def __init__(self):
        super(FFNeuralNet,self).__init__() 
        self.layer1 = nn.Linear(784,100) #linear layer with input size 784 and output size 100
        self.layer2 = nn.Linear(100,10)
        self.sigmoid = nn.Sigmoid()
    def forward(self,t) :
            t = self.layer1(t)
            t = self.sigmoid(t)
            t = self.layer2(t)
            t = F.softmax(t, dim=1)
            print(t.size())
            return t

In [3]:
net = FFNeuralNet()
print(net)

FFNeuralNet(
  (layer1): Linear(in_features=784, out_features=100, bias=True)
  (layer2): Linear(in_features=100, out_features=10, bias=True)
  (sigmoid): Sigmoid()
)


In [4]:
params = list(net.parameters())
print('No. of parameters :'+str(len(params)))
print('\nDimensions of first layer weights: '+str(params[0].size())) # Weights of fc1
print('Dimensions of first layer bias: '+str(params[1].size())) # Biases of fc1
print('\nDimensions of second layer weights: '+str(params[2].size())) # Weights of fc2
print('Dimensions of second layer bias: '+str(params[3].size())) # Biases of fc2

totalParams = 0
for param in params:    
#     print(param.size())
    totalParams += np.sum(np.prod(param.size()))
print('\nTotal number of parameters: '+str(totalParams))

No. of parameters :4

Dimensions of first layer weights: torch.Size([100, 784])
Dimensions of first layer bias: torch.Size([100])

Dimensions of second layer weights: torch.Size([10, 100])
Dimensions of second layer bias: torch.Size([10])

Total number of parameters: 79510


In [5]:
train_dataset = torchvision.datasets.MNIST(root='./data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),  
                                           download=True)
#creating dataloader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=1, 
                                           shuffle=True, num_workers = 4)


In [6]:
for i,data in enumerate(train_loader):
    inputs,labels = data
    print(inputs.view(inputs.shape[0],-1).shape)

torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1, 784])
torch.Size([1

In [7]:
inputs.view(-1,inputs.shape[0]).shape

torch.Size([784, 1])

In [8]:
data1 = next(iter(train_loader))

In [9]:
input1,label = data1 #implementing feed forward neural network for one image

In [10]:
label

tensor([2])

In [11]:
net(input1.view(input1.shape[0],-1)) 

torch.Size([1, 10])


tensor([[0.1029, 0.0454, 0.0669, 0.1079, 0.1625, 0.1447, 0.0632, 0.0829, 0.1407,
         0.0828]], grad_fn=<SoftmaxBackward>)

In [12]:
tensor_image = input1.view(input1.shape[2],input1.shape[3])
print(type(input1), input1.shape)

<class 'torch.Tensor'> torch.Size([1, 1, 28, 28])


In [13]:
transforms.ToPILImage()(tensor_image).show() #displaying the image 

# 2)Convolutional Neural Network

In [15]:
class LeNet(nn.Module):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5)
        self.pool1 = nn.MaxPool2d(kernel_size=2,stride=2)
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)
        self.pool2 = nn.MaxPool2d(kernel_size=2,stride=2)        
        self.fc1 = nn.Linear(400, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool1(x)
        x = F.relu(self.conv2(x))
        x = self.pool2(x)
        x = x.view(-1, 400)
        x = F.relu(self.fc1(x)) 
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return F.softmax(x,dim=1)

In [16]:
net = LeNet()
print(net)

LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [17]:
params = list(net.named_parameters())
print('No. of parameters : '+str(len(params))+'\n')

totalParams = 0
for name, param in params:    
    print(name,'-->', param.shape)
    totalParams += np.sum(np.prod(param.size()))
print('\nTotal number of parameters: '+str(totalParams))

No. of parameters : 10

conv1.weight --> torch.Size([6, 1, 5, 5])
conv1.bias --> torch.Size([6])
conv2.weight --> torch.Size([16, 6, 5, 5])
conv2.bias --> torch.Size([16])
fc1.weight --> torch.Size([120, 400])
fc1.bias --> torch.Size([120])
fc2.weight --> torch.Size([84, 120])
fc2.bias --> torch.Size([84])
fc3.weight --> torch.Size([10, 84])
fc3.bias --> torch.Size([10])

Total number of parameters: 61706


In [18]:
apply_transform = transforms.Compose([transforms.Resize(32), transforms.ToTensor()])
Batchsize  = 1
trainset = datasets.MNIST(root = './data', train  = True, download  = True, transform = apply_transform)
#creating dataloader
trainLoader = torch.utils.data.DataLoader(trainset, batch_size  = Batchsize,shuffle  = True)

In [19]:
for i,data in enumerate(trainLoader):
    input,labels = data
    print(input.shape)

torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
torch.Size([1, 1, 32, 32])
t

In [20]:
data1 = next(iter(trainLoader))

In [21]:
input1,label = data1

In [22]:
label

tensor([4])

In [23]:
b = net(input1)

In [24]:
b

tensor([[0.0967, 0.1093, 0.0923, 0.0929, 0.0937, 0.1074, 0.0962, 0.1072, 0.0987,
         0.1056]], grad_fn=<SoftmaxBackward>)